var langLayoutObj = {
    'BG-BG': {
        'Apply theme': 'Прилагане на тема: ',
        'Cancel': 'Отказ',
        'Choose your favorite theme.': 'Изберете любимата си тема.',
        'Current time zone': 'Текуща часова зона',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Обратна връзка',
        'Feedback Comment': 'Въведете вашия коментар', 
        'Feedback Dont Like': 'Не ми харесва нещо',
        'Feedback Like': 'Харесва ми нещо',
        'Feedback Suggestion': 'Имам предложение',
        'Feedback Question': 'Какъв вид обратна връзка имате??',
        'Help': 'Помощ',
        'Include screenshot':'Включване на екранна снимка',
        'Language': 'Език',
        'Language and time zone': 'Език и часова зона',
        'My account': 'Моят акаунт',
        'My accounts': 'Моите акаунти',
        'My profile': 'За мен',
        'Notifications': 'Известия',
        'Off': 'Изкл.',
        'On': 'Вкл.',
        'Privacy Statement': 'Декларация за поверителност',
        'Save': 'Запиши',
        'Selected theme': 'Избрана тема: ',
        'Settings': 'Настройки',
        'Sign out': 'Излизане',
        'Submit': 'Подай',
        'Title Frown': 'Какво не ви хареса?',
        'Title Idea': 'Какво предлагате?',
        'Title Smile': 'Какво ви хареса?',
        'Theme': 'Тема',
        'Your apps': 'Вашите приложения'
    },
    'CS-CZ': {
        'Apply theme': 'Použít motiv: ',
        'Cancel': 'Zrušit',
        'Choose your favorite theme.': 'Zvolte svůj oblíbený motiv.',
        'Current time zone': 'Aktuální časové pásmo',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Váš názor',
        'Feedback Comment': 'Zadejte prosím svůj komentář.',
        'Feedback Dont Like': 'Něco se mi nelíbí',
        'Feedback Like': 'Něco se mi líbí',
        'Feedback Suggestion': 'Mám návrh',
        'Feedback Question': 'Co byste nám chtěli říct?',
        'Help': 'Nápověda',
        'Include screenshot':'Zahrnout screenshot',
        'Language': 'Jazyk',
        'Language and time zone': 'Jazyk a časové pásmo',
        'My account': 'Můj účet',
        'My accounts': 'Moje účty',
        'My profile': 'O mně',
        'Notifications': 'Oznámení',
        'Off': 'Vypnuto',
        'On': 'Zapnuto',
        'Privacy Statement': 'Prohlášení o zásadách ochrany osobních údajů',
        'Save': 'Uložit',
        'Selected theme': 'Vybraný motiv: ',
        'Settings': 'Nastavení',
        'Sign out': 'Odhlásit se',
        'Submit': 'Odeslat',
        'Title Frown': 'Co se vám nelíbilo?',
        'Title Idea': 'Co navrhujete?',
        'Title Smile': 'Co se vám líbilo?',
        'Theme': 'Motiv',
        'Your apps': 'Vaše aplikace'
    },
    'DE-AT': {
        'Apply theme': 'Design anwenden: ',
        'Cancel': 'Abbrechen',
        'Choose your favorite theme.': 'Wählen Sie Ihr Lieblingsdesign aus.',
        'Current time zone': 'Aktuelle Zeitzone',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Feedback',
        'Feedback Comment': 'Bitte geben Sie Ihren Kommentar ein.',
        'Feedback Dont Like': 'Mir gefällt etwas nicht',
        'Feedback Like': 'Mir gefällt etwas',
        'Feedback Suggestion': 'Ich habe einen Vorschlag',
        'Feedback Question': 'Welche Art von Feedback haben Sie?',
        'Help': 'Hilfe',
        'Include screenshot':'Screenshot einschließen',
        'Language': 'Sprache',
        'Language and time zone': 'Sprache und Zeitzone',
        'My account': 'Mein Konto',
        'My accounts': 'Meine Konten',
        'My profile': 'Über mich',
        'Notifications': 'Benachrichtigungen',
        'Off': 'Aus',
        'On': 'Ein',
        'Privacy Statement': 'Datenschutzbestimmungen',
        'Save': 'Speichern',
        'Selected theme': 'Ausgewähltes Design: ',
        'Settings': 'Einstellungen',
        'Sign out': 'Abmelden',
        'Submit': 'Absenden',
        'Title Frown': 'Was hat Ihnen nicht gefallen?',
        'Title Idea': 'Was schlagen Sie vor?',
        'Title Smile': 'Was hat Ihnen gefallen?',
        'Theme': 'Design',
        'Your apps': 'Ihre Apps'
    },
    'ET-EE': {
        'Apply theme': 'Rakenda kujundus: ',
        'Cancel': 'Loobu',
        'Choose your favorite theme.': 'Saate valida oma lemmikkujunduse.',
        'Current time zone': 'Praegune ajavöönd',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Tagasiside',
        'Feedback Comment': 'Kirjutage kommentaar',
        'Feedback Dont Like': 'On midagi, mis mulle ei meeldi',
        'Feedback Like': 'On midagi, mis mulle meeldib',
        'Feedback Suggestion': 'Mul on ettepanek',
        'Feedback Question': 'Millist tagasisidet soovite meile anda?',
        'Help': 'Spikker',
        'Include screenshot':'Kaasa kuvatõmmis',
        'Language': 'Keel',
        'Language and time zone': 'Keel ja ajavöönd',
        'My account': 'Minu konto',
        'My accounts': 'Minu kontod',
        'My profile': 'Minust',
        'Notifications': 'Teatised',
        'Off': 'Väljas',
        'On': 'Sees',
        'Privacy Statement': 'Privaatsusavaldus',
        'Save': 'Salvesta',
        'Selected theme': 'Valitud kujundus: ',
        'Settings': 'Sätted',
        'Sign out': 'Logi välja',
        'Submit': 'Edasta',
        'Title Frown': 'Mis teile ei meeldinud?',
        'Title Idea': 'Mida soovitate?',
        'Title Smile': 'Mis teile meeldis?',
        'Theme': 'Kujundus',
        'Your apps': 'Teie rakendused'
    },
    'EN-GB': {
        'Apply theme': 'Apply theme: ',
        'Cancel': 'Cancel',
        'Choose your favorite theme.': 'Choose your favorite theme.',
        'Current time zone': 'Current time zone',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Feedback',
        'Feedback Comment': 'Please type in your comment',
        'Feedback Dont Like': 'I Don\'t Like Something',
        'Feedback Like': 'I Like Something',
        'Feedback Suggestion': 'I Have a Suggestion',
        'Feedback Question': 'What kind of feedback do you have?',
        'Help': 'Help',
        'Include screenshot':'Include screenshot',
        'Language': 'Language',
        'Language and time zone': 'Language and time zone',
        'My account': 'My account',
        'My accounts': 'My accounts',
        'My profile': 'My profile',
        'Notifications': 'Notifications',
        'Off': 'Off',
        'On': 'On',
        'Privacy Statement': 'Privacy Statement',
        'Save': 'Save',
        'Selected theme': 'Selected theme: ',
        'Settings': 'Settings',
        'Sign out': 'Sign out',
        'Submit': 'Submit',
        'Title Frown': 'What did you not like?',
        'Title Idea': 'What do you suggest?',
        'Title Smile': 'What did you like?',
        'Theme': 'Theme',
        'Your apps': 'Your apps'
    },
    'HR-HR': {
        'Apply theme': 'Primijeni temu: ',
        'Cancel': 'Odustani',
        'Choose your favorite theme.': 'Odaberite omiljenu temu.',
        'Current time zone': 'Trenutna vremenska zona',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Povratne informacije',
        'Feedback Comment': 'Unesite komentar',
        'Feedback Question': 'Kakve povratne informacija imate?',
        'Feedback Like': 'Sviđa mi se nešto',
        'Feedback Dont Like': 'Ne sviđa mi se nešto',
        'Feedback Suggestion': 'Imam prijedlog',
        'Help': 'Pomoć',
        'Include screenshot':'Uvrsti snimku zaslona',
        'Language': 'Jezik',
        'Language and time zone': 'Jezik i vremenska zona',
        'My account': 'Moj račun',
        'My accounts': 'Moji računi',
        'My profile': 'O meni',
        'Notifications': 'Obavijesti',
        'Off': 'Isključeno',
        'On': 'Uključeno',
        'Privacy Statement': 'Izjava o zaštiti privatnosti',
        'Save': 'Spremi',
        'Selected theme': 'Odabrana tema: ',
        'Settings': 'Postavke',
        'Sign out': 'Odjava',
        'Submit': 'Pošalji',
        'Title Frown': 'Što vam se nije svidjelo?',
        'Title Idea': 'Što predlažete?',
        'Title Smile': 'Što vam se svidjelo?',
        'Theme': 'Tema',
        'Your apps': 'Vaše aplikacije'
    },
    'HU-HU': {
        'Apply theme': 'Téma alkalmazása: ',
        'Cancel': 'Mégse',
        'Choose your favorite theme.': 'A kedvenc téma kiválasztása.',
        'Current time zone': 'Jelenlegi időzóna',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Visszajelzés',
        'Feedback Comment': 'Kérjük, írja be az észrevételét',
        'Feedback Dont Like': 'Nem tetszik valami',
        'Feedback Like': 'Tetszik valami',
        'Feedback Suggestion': 'Van egy javaslatom',
        'Feedback Question': 'Milyen jellegű visszajelzést szeretne írni?',
        'Help': 'Súgó',
        'Include screenshot':'Képernyőképpel együtt',
        'Language': 'Nyelv',
        'Language and time zone': 'Nyelv és időzóna',
        'My account': 'Saját fiók',
        'My accounts': 'Saját fiókok',
        'My profile': 'Rólam',
        'Notifications': 'Értesítések',
        'Off': 'Kikapcsolva',
        'On': 'Bekapcsolva',
        'Privacy Statement': 'Adatvédelmi nyilatkozat',
        'Save': 'Mentés',
        'Selected theme': 'Választott téma: ',
        'Settings': 'Beállítások',
        'Sign out': 'Kijelentkezés',
        'Submit': 'Küldés',
        'Title Frown': 'Mi nem tetszett?',
        'Title Idea': 'Milyen javaslata van?',
        'Title Smile': 'Mi tetszett?',
        'Theme': 'Téma',
        'Your apps': 'Saját appok'
    },
    'KK-KZ': {
        'Apply theme': 'Тақырыпты қолдану: ',
        'Cancel': 'Бас тарту',
        'Choose your favorite theme.': 'Сүйікті тақырыбыңызды таңдаңыз.',
        'Current time zone': 'Ағымдағы уақыт белдеуі',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Пікір',
        'Feedback Comment': 'Комментарийіңізді енгізіңіз',
        'Feedback Dont Like': 'Маған бірдеңе ұнамайды',
        'Feedback Like': 'Маған бірдеңе ұнады',
        'Feedback Suggestion': 'Менде ұсыныс бар',
        'Feedback Question': 'Қандай пікір қалдырғыңыз келеді?',
        'Help': 'Анықтама',
        'Include screenshot':'Скриншотты қосу',
        'Language': 'Тіл',
        'Language and time zone': 'Тіл және уақыт белдеуі',
        'My account': 'Менің тіркелгім',
        'My accounts': 'Менің тіркелгілерім',
        'My profile': 'Мен туралы мәлімет',
        'Notifications': 'Хабарландырулар',
        'Off': 'Өшіру',
        'On': 'Қосу',
        'Privacy Statement': 'Құпиялылық туралы мәлімдеме',
        'Save': 'Сақтау',
        'Selected theme': 'Таңдалған тақырып: ',
        'Settings': 'Параметрлер',
        'Sign out': 'Шығу',
        'Submit': 'Жіберу',
        'Title Frown': 'Сізге не ұнамады?',
        'Title Idea': 'Не ұсынар едіңіз?',
        'Title Smile': 'Сізге не ұнады?',
        'Theme': 'Тақырып',
        'Your apps': 'Бағдарламаларыңыз'
    },
    'LT-LT': {
        'Apply theme': 'Taikyti temą: ',
        'Cancel': 'Atšaukti',
        'Choose your favorite theme.': 'Pasirinkite mėgstamą temą.',
        'Current time zone': 'Dabartinė laiko juosta',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Atsiliepimai',
        'Feedback Comment': 'Įrašykite savo komentarą',
        'Feedback Dont Like': 'Man kažkas nepatinka',
        'Feedback Like': 'Man kažkas patinka',
        'Feedback Suggestion': 'Turiu pasiūlymą',
        'Feedback Question': 'Kokių atsiliepimų turite?',
        'Help': 'Žinynas',
        'Include screenshot':'Įtraukti ekrano kopiją',
        'Language': 'Kalba',
        'Language and time zone': 'Kalba ir laiko juosta',
        'My account': 'Mano paskyra',
        'My accounts': 'Mano paskyros',
        'My profile': 'Apie mane',
        'Notifications': 'Pranešimai',
        'Off': 'Išjungta',
        'On': 'Įjungta',
        'Privacy Statement': 'Privatumo patvirtinimas',
        'Save': 'Įrašyti',
        'Selected theme': 'Pasirinkta tema: ',
        'Settings': 'Parametrai',
        'Sign out': 'Atsijungti',
        'Submit': 'Pateikti',
        'Title Frown': 'Kas jums nepatiko?',
        'Title Idea': 'Ką siūlote?',
        'Title Smile': 'Kas jums patiko?',
        'Theme': 'Tema',
        'Your apps': 'Jūsų programos'
    },
    'PL-PL': {
        'Apply theme': 'Zastosuj motyw: ',
        'Cancel': 'Anuluj',
        'Choose your favorite theme.': 'Wybierz ulubiony motyw.',
        'Current time zone': 'Bieżąca strefa czasowa',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Opinia',
        'Feedback Comment': 'Wpisz swój komentarz',
        'Feedback Dont Like': 'Coś mi się nie podoba',
        'Feedback Like': 'Coś mi się podoba',
        'Feedback Suggestion': 'Mam sugestię',
        'Feedback Question': 'Jakiego rodzaju opinię chcesz przekazać?',
        'Help': 'Pomoc',
        'Include screenshot':'Dołącz zrzut ekranu',
        'Language': 'Język',
        'Language and time zone': 'Język i strefa czasowa',
        'My account': 'Moje konto',
        'My accounts': 'Moje konta',
        'My profile': 'O mnie',
        'Notifications': 'Powiadomienia',
        'Off': 'Wyłączone',
        'On': 'Włączone',
        'Privacy Statement': 'Zasady zachowania poufności informacji',
        'Save': 'Zapisz',
        'Selected theme': 'Wybrany motyw: ',
        'Settings': 'Ustawienia',
        'Sign out': 'Wyloguj',
        'Submit': 'Prześlij',
        'Title Frown': 'Co Ci się nie spodobało?',
        'Title Idea': 'Co sugerujesz?',
        'Title Smile': 'Co Ci się spodobało?',
        'Theme': 'Motyw',
        'Your apps': 'Twoje aplikacje'
    },
    'RO-RO': {
        'Apply theme': 'Aplicați tema: ',
        'Cancel': 'Anulare',
        'Choose your favorite theme.': 'Alegeți tema preferată.',
        'Current time zone': 'Fus orar actual',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Feedback',
        'Feedback Comment': 'Introduceți un comentariu',
        'Feedback Dont Like': 'Nu îmi place ceva',
        'Feedback Like': 'Îmi place ceva',
        'Feedback Suggestion': 'Am o sugestie',
        'Feedback Question': 'Ce fel de feedback aveți?',
        'Help': 'Ajutor',
        'Include screenshot':'Includeți captura de ecran',
        'Language': 'Limbă',
        'Language and time zone': 'Limbă și fus orar',
        'My account': 'Contul meu',
        'My accounts': 'Conturile mele',
        'My profile': 'Despre mine',
        'Notifications': 'Notificări',
        'Off': 'Dezactivat',
        'On': 'Activat',
        'Privacy Statement': 'Angajament de respectare a confidențialității',
        'Save': 'Salvare',
        'Selected theme': 'Tema selectată: ',
        'Settings': 'Setări',
        'Sign out': 'Deconectare',
        'Submit': 'Remitere',
        'Title Frown': 'Ce nu v-a plăcut?',
        'Title Idea': 'Ce sugerați?',
        'Title Smile': 'Ce v-a plăcut?',
        'Theme': 'Temă',
        'Your apps': 'Aplicațiile dvs.'
    },
    'SR-LATN-CS': {
        'Apply theme': 'Primena teme: ',
        'Cancel': 'Otkaži',
        'Choose your favorite theme.': 'Odaberite svoju omiljenu temu.',
        'Current time zone': 'Trenutna vremenska zona',       
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Povratne informacije',
        'Feedback Comment': 'Otkucajte komentar',
        'Feedback Question': 'Koju vrstu povratnih informacija imate?',
        'Feedback Like': 'Sviđa mi se nešto',
        'Feedback Dont Like': 'Ne sviđa mi se nešto',
        'Feedback Suggestion': 'Imam predlog',
        'Help': 'Pomoć',
        'Include screenshot':'Dodaj snimak ekrana',
        'Language': 'Jezik',
        'Language and time zone': 'Jezik i vremenska zona',
        'My account': 'Moj nalog',
        'My accounts': 'Moji nalozi',
        'My profile': 'O meni',
        'Notifications': 'Obaveštenja',
        'Off': 'Isključeno',
        'On': 'Uključeno',
        'Privacy Statement': 'Izjava o privatnosti',
        'Save': 'Sačuvaj',
        'Selected theme': 'Izabrana tema: ',
        'Settings': 'Postavke',
        'Sign out': 'Odjavi se',
        'Submit': 'Prosledi',
        'Title Frown': 'Šta vam se nije svidelo?',
        'Title Idea': 'Šta predlažete?',
        'Title Smile': 'Šta vam se svidelo?',
        'Theme': 'Tema',
        'Your apps': 'Vaše aplikacije'
    },
    'RU-RU': {
        'Apply theme': 'Применить тему: ',
        'Cancel': 'Отмена',
        'Choose your favorite theme.': 'Выберите понравившуюся тему.',
        'Current time zone': 'Текущий часовой пояс',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Отзыв',
        'Feedback Comment': 'Введите свой комментарий',
        'Feedback Dont Like': 'Мне кое-что не нравится',
        'Feedback Like': 'Мне кое-что нравится',
        'Feedback Suggestion': 'У меня есть предложение',
        'Feedback Question': 'Какой отзыв вы хотите оставить?',
        'Help': 'Справка',
        'Include screenshot':'Включить снимок экрана',
        'Language': 'Язык',
        'Language and time zone': 'Язык и часовой пояс',
        'My account': 'Моя учетная запись',
        'My accounts': 'Мои учетные записи',
        'My profile': 'Мои данные',
        'Notifications': 'Уведомления',
        'Off': 'Выкл.',
        'On': 'Вкл.',
        'Privacy Statement': 'Заявление о конфиденциальности',
        'Save': 'Сохранить',
        'Selected theme': 'Выбранная тема: ',
        'Settings': 'Параметры',
        'Sign out': 'Выйти',
        'Submit': 'Отправить',
        'Title Frown': 'Что вам не нравится?',
        'Title Idea': 'Что вы хотите предложить?',
        'Title Smile': 'Что вам нравится?',
        'Theme': 'Тема',
        'Your apps': 'Ваши приложения'
    },
    'SL-SI': {
        'Apply theme': 'Uporabite temo: ',
        'Cancel': 'Prekliči',
        'Choose your favorite theme.': 'Izberite priljubljeno temo.',
        'Current time zone': 'Trenutni časovni pas',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Povratne informacije',
        'Feedback Comment': 'Vnesite svojo pripombo',
        'Feedback Dont Like': 'Nekaj mi ni všeč',
        'Feedback Like': 'Nekaj mi je všeč',
        'Feedback Suggestion': 'Imam predlog',
        'Feedback Question': 'Kakšne povratne informacije imate?',
        'Help': 'Pomoč',
        'Include screenshot':'Vključi posnetek zaslona',
        'Language': 'Jezik',
        'Language and time zone': 'Jezik in časovni pas',
        'My account': 'Moj račun',
        'My accounts': 'Moji računi',
        'My profile': 'O meni',
        'Notifications': 'Obvestila',
        'Off': 'Izklopljeno',
        'On': 'Vklopljeno',
        'Privacy Statement': 'Izjava o zasebnosti',
        'Save': 'Shrani',
        'Selected theme': 'Izbrana tema: ',
        'Settings': 'Nastavitve',
        'Sign out': 'Izpis',
        'Submit': 'Pošlji',
        'Title Frown': 'Kaj vam ni bilo všeč?',
        'Title Idea': 'Kakšen je vaš predlog?',
        'Title Smile': 'Kaj vam je všeč?',
        'Theme': 'Tema',
        'Your apps': 'Vaše aplikacije'
    },
    'SK-SK': {
        'Apply theme': 'Použiť motív: ',
        'Cancel': 'Zrušiť',
        'Choose your favorite theme.': 'Vyberte si obľúbený motív.',
        'Current time zone': 'Aktuálne časové pásmo',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Pripomienky',
        'Feedback Comment': 'Zadajte svoj komentár',
        'Feedback Dont Like': 'Niečo sa mi nepáči',
        'Feedback Like': 'Niečo sa mi páči',
        'Feedback Suggestion': 'Mám návrh',
        'Feedback Question': 'Aký typ pripomienok chcete poskytnúť?',
        'Help': 'Pomocník',
        'Include screenshot':'Zahrnúť snímku obrazovky',
        'Language': 'Jazyk',
        'Language and time zone': 'Jazyk a časové pásmo',
        'My account': 'Moje konto',
        'My accounts': 'Moje kontá',
        'My profile': 'O mne',
        'Notifications': 'Oznámenia',
        'Off': 'Vypnuté',
        'On': 'Zapnuté',
        'Privacy Statement': 'Vyhlásenie o ochrane osobných údajov',
        'Save': 'Uložiť',
        'Selected theme': 'Vybratý motív: ',
        'Settings': 'Nastavenie',
        'Sign out': 'Odhlásiť sa',
        'Submit': 'Odoslať',
        'Title Frown': 'Čo sa vám nepáčilo?',
        'Title Idea': 'Čo navrhujete?',
        'Title Smile': 'Čo sa vám páčilo?',
        'Theme': 'Motív',
        'Your apps': 'Vaše aplikácie'
    },
    'TR-TR': {
        'Apply theme': 'Temayı uygula: ',
        'Cancel': 'İptal',
        'Choose your favorite theme.': 'Beğendiğiniz temayı seçin.',
        'Current time zone': 'Geçerli saat dilimi',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Geri bildirim',
        'Feedback Comment': 'Lütfen yorumunuzu yazın',
        'Feedback Dont Like': 'Beğenmediğim Bir Şey Var',
        'Feedback Like': 'Beğendiğim Bir Özellik Var',
        'Feedback Suggestion': 'Bir Önerim Var',
        'Feedback Question': 'Ne tür bir geri bildirimde bulunmak istiyorsunuz?',
        'Help': 'Yardım',
        'Include screenshot':'Ekran görüntüsü ekle',
        'Language': 'Dil',
        'Language and time zone': 'Dil ve saat dilimi',
        'My account': 'Hesabım',
        'My accounts': 'Hesaplarım',
        'My profile': 'Hakkımda',
        'Notifications': 'Bildirimler',
        'Off': 'Kapalı',
        'On': 'Açık',
        'Privacy Statement': 'Gizlilik Bildirimi',
        'Save': 'Kaydet',
        'Selected theme': 'Seçili tema: ',
        'Settings': 'Ayarlar',
        'Sign out': 'Oturumu kapat',
        'Submit': 'Gönder',
        'Title Frown': 'Neleri beğenmediniz?',
        'Title Idea': 'Ne önerirsiniz?',
        'Title Smile': 'Neleri beğendiniz?',
        'Theme': 'Tema',
        'Your apps': 'Uygulamalarınız'
    },
    'UK-UA': {
        'Apply theme': 'Застосувати тему: ',
        'Cancel': 'Скасувати',
        'Choose your favorite theme.': 'Виберіть улюблену тему.',
        'Current time zone': 'Поточний часовий пояс',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Feedback': 'Відгук',
        'Feedback Comment': 'Введіть свій коментар',
        'Feedback Dont Like': 'Мені дещо не подобається',
        'Feedback Like': 'Мені дещо подобається',
        'Feedback Suggestion': 'У мене є пропозиція',
        'Feedback Question': 'Який у вас відгук?',
        'Help': 'Довідка',
        'Include screenshot':'Додати знімок екрана',
        'Language': 'Мова',
        'Language and time zone': 'Мова та часовий пояс',
        'My account': 'Мій обліковий запис',
        'My accounts': 'Мої облікові записи',
        'My profile': 'Про мене',
        'Notifications': 'Сповіщення',
        'Off': 'Вимк.',
        'On': 'Увімк.',
        'Privacy Statement': 'Декларація про конфіденційність',
        'Save': 'Зберегти',
        'Selected theme': 'Вибрана тема: ',
        'Settings': 'Параметри',
        'Sign out': 'Вийти',
        'Submit': 'Надіслати',
        'Title Frown': 'Що саме вам не сподобалося?',
        'Title Idea': 'Що ви пропонуєте?',
        'Title Smile': 'Що саме вам сподобалося?',
        'Theme': 'Тема',
        'Your apps': 'Ваші програми'
    }
}