var headerObj = {
    "use outlook settings": false,
    "use user property extensions": true,
    "app launcher": true,
    "environment": true,
    "notifications": true,
    "settings": true,
    "help": true,
    "account": true,
    "theme settings": true,
    "feedback": false,
    "feedbackurl": "",
    "maximize": false,
    "mailbox photo": false,
    "themes": "./defs/themes.json.js",
    "phraseapp": false,
    "phraseapp project id": "",
    "phraseapp prefix": "[[__",
    "phraseapp suffix": "__]]",
    "form width percent": "",
    "processtext": "Overridden text",
    "elearningtext": "",
    "autocalc": "focuschange",
    "calc_js_path": "https://sasa-test-misc-wap.azurewebsites.net/calc/calc_amulbintocwithotherchanges.js",
    "calc_js_setting": "",
    "calc_conf_path": "",
    "calc_conf_setting": "",
    "calc_api_path": "https://sasa-test-ete-fnc.azurewebsites.net/Calculation('{calcname}/{calcversion}')/Calculate",
    "action loading":"Form('{formname}/{formversion}')/Loading",
    "bing maps key": "",
    "map wrapper id": "",
    "map route info wrapper id": "",
    "map country name": "",
    "map zoom": "",
    "map center pushpin": true,
    "map center pushpin title": "",
    "map center pushpin subtitle": "",
    "map center pushpin description": "",
    "map center latitude": "",
    "map center longitude": "",
    "map show info box": true,
    "map show traffic": ""
};