var headerObj = {
    "use outlook settings": true,
    "use user property extensions": true,
    "app launcher": true,
    "environment": true,
    "notifications": true,
    "settings": true,
    "help": true,
    "account": true,
    "theme settings": true,
    "feedback": false,
    "maximize": false,
    "mailbox photo": true,
    "themes": "./defs/themes.json.js",
    "phraseapp": false,
    "phraseapp project id": "",
    "phraseapp prefix": "[[__",
    "phraseapp suffix": "__]]",
    "form width percent": "",
    "processtext": "",
    "elearningtext": ""
};