var headerObj = {
    "use outlook settings": false,
    "use user property extensions": true,
    "app launcher": true,
    "environment": true,
    "notifications": true,
    "settings": true,
    "help": true,
    "account": true,
    "theme settings": true,
    "feedback": false,
    "feedbackurl": "",
    "maximize": false,
    "mailbox photo": false,
    "themes": "./defs/themes.json.js",
    "phraseapp": false,
    "phraseapp project id": "",
    "phraseapp prefix": "[[__",
    "phraseapp suffix": "__]]",
    "form width percent": "",
    "processtext": "Overridden text",
    "elearningtext": "",
    "autocalc": "",
    "calc_js_path": "",
    "calc_js_setting": "",
    "calc_conf_path": "",
    "calc_conf_setting": "",
    "calc_api_path": "",
    "action":"Form('{formname}/{formversion}')/Submit",
    "action local script" : "",
    "action loading":"Form('{formname}/{formversion}')/Loading",
    "action loaded":"Form('{formname}/{formversion}')/Loaded",
    "action focus":"Form('{formname}/{formversion}')/Focus",
    "action focus local script":"",
    "action blur":"Form('{formname}/{formversion}')/Blur",
    "action blur local script":"",
    "action change":"Form('{formname}/{formversion}')/Change",
    "action change local script":"",
    "action search":"Form('{formname}/{formversion}')/Search",
    "action search local script":"",
    "action showDropdown":"Form('{formname}/{formversion}')/ShowDropdown",
    "action showDropdown local script":"",
    "action click":"Form('{formname}/{formversion}')/Click",
    "action click local script":"",
    "action dblclick":"Form('{formname}/{formversion}')/DblClick",
    "action dblclick local script":"",
    "action mouseover":"Form('{formname}/{formversion}')/MouseOver",
    "action mouseover local script":"",
    "action mousedown":"Form('{formname}/{formversion}')/MouseDown",
    "action mousedown local script":"",
    "action mouseout":"Form('{formname}/{formversion}')/MouseOut",
    "action mouseout local script":"",
    "action mouseup":"Form('{formname}/{formversion}')/MouseUp",
    "action mouseup local script":"",
    "action mousemove":"Form('{formname}/{formversion}')/MouseMove",
    "action mousemove local script":"",
    "action keypress":"Form('{formname}/{formversion}')/KeyPress",
    "action keypress local script":"",
    "action keyup":"Form('{formname}/{formversion}')/KeyUp",
    "action keyup local script":"",
    "action keydown":"Form('{formname}/{formversion}')/KeyDown",
    "action keydown local script":"",
    "action prevPage":"Form('{formname}/{formversion}')/PrevPage",
    "action prevPage local script":"",
    "action nextPage":"Form('{formname}/{formversion}')/NextPage",
    "action nextPage local script":"",
    "action componentError":"Form('{formname}/{formversion}')/ComponentError",
    "action componentError local script":"",
    "bing maps key": "",
    "map wrapper id": "",
    "map route info wrapper id": "",
    "map country name": "",
    "map zoom": "",
    "map center pushpin": true,
    "map center pushpin title": "",
    "map center pushpin subtitle": "",
    "map center pushpin description": "",
    "map center latitude": "",
    "map center longitude": "",
    "map show info box": true,
    "map show traffic": "",
    "toggle menu": false,
    "triggerResizeChange": false,
    "userlangs": "./defs/userlangs.json.js",
    "defaultLanguage": "EN-GB",
    "timezones": "./defs/timezones.json.js",
    "defaultTimeZone": "UTC",
    "disableActionSpinner": false,
    "menus": "",
    "langmenustop": "",
    "langmenusbottom": "",
    "test": false,
    "debug": false,
    "choicesOptions": ""
};