var userLangsObj = {
    "BG-BG" : 'български (България&nbsp;-&nbsp;BG)',
    "CS-CZ" : 'čeština (Česká&nbsp;republika&nbsp;-&nbsp;CZ)',
    "DE-AT" : 'Deutsch (Österreich&nbsp;-&nbsp;AT)',
    "ET-EE" : 'eesti (Eesti&nbsp;-&nbsp;EE)',
    "EN-GB" : 'English (United&nbsp;Kingdom&nbsp;-&nbsp;GB)',
    "HR-HR" : 'hrvatski (Hrvatska&nbsp;-&nbsp;HR)',
    "HU-HU" : 'magyar (Magyarország&nbsp;-&nbsp;HU)',
    "KK-KZ" : 'Қазақ (Қазақстан&nbsp;-&nbsp;KZ)',
    "LT-LT" : 'lietuvių (Lietuva&nbsp;-&nbsp;LT)',
    "PL-PL" : 'polski (Polska&nbsp;-&nbsp;PL)',
    "RO-RO" : 'română (România&nbsp;-&nbsp;RO)',
    "SR-LATN-CS" : 'srpski (Srbija&nbsp;-&nbsp;RS)',
    "RU-RU" : 'русский (Россия&nbsp;-&nbsp;RU)',
    "SL-SI" : 'slovenščina (Slovenija&nbsp;-&nbsp;SI)',
    "SK-SK" : 'slovenčina (Slovensko&nbsp;-&nbsp;SK)', 
    "TR-TR" : 'Türkçe (Türkiye&nbsp;-&nbsp;TR)',
    "UK-UA" : 'українська (Україна&nbsp;-&nbsp;UA)'
}; 
