var formObj = {
	"type": "form",
	"tags": [],
	"owner": "599d5130a0434200072250ab",
	"components": [{
		"autofocus": false,
		"input": true,
		"tableView": true,
		"inputType": "number",
		"label": "Number a",
		"key": "a",
		"placeholder": "",
		"prefix": "",
		"suffix": "",
		"defaultValue": "",
		"protected": false,
		"persistent": true,
		"hidden": false,
		"clearOnHide": true,
		"validate": {
			"required": false,
			"min": "",
			"max": "",
			"step": "any",
			"integer": "",
			"multiple": "",
			"custom": "",
			"customPrivate": false
		},
		"type": "number",
		"labelPosition": "top",
		"tags": [],
		"conditional": {
			"show": "",
			"when": null,
			"eq": ""
		},
		"properties": {
			
		},
		"lockKey": true,
		"customClass": "",
		"multiple": false,
		"unique": false,
		"labelWidth": 30,
		"labelMargin": 3,
		"description": "",
		"errorLabel": "",
		"tooltip": "",
		"hideLabel": false,
		"tabindex": "",
		"disabled": false,
		"dbIndex": false,
		"customDefaultValue": "",
		"calculateValue": "",
		"id": "e65btpj"
	},
	{
		"autofocus": false,
		"input": true,
		"tableView": true,
		"inputType": "number",
		"label": "Number b",
		"key": "b",
		"placeholder": "",
		"prefix": "",
		"suffix": "",
		"defaultValue": "",
		"protected": false,
		"persistent": true,
		"hidden": false,
		"clearOnHide": true,
		"validate": {
			"required": false,
			"min": "",
			"max": "",
			"step": "any",
			"integer": "",
			"multiple": "",
			"custom": "",
			"customPrivate": false
		},
		"type": "number",
		"labelPosition": "top",
		"tags": [],
		"conditional": {
			"show": "",
			"when": null,
			"eq": ""
		},
		"properties": {
			
		},
		"lockKey": true,
		"isNew": false,
		"customClass": "",
		"multiple": false,
		"unique": false,
		"labelWidth": 30,
		"labelMargin": 3,
		"description": "",
		"errorLabel": "",
		"tooltip": "",
		"hideLabel": false,
		"tabindex": "",
		"disabled": false,
		"dbIndex": false,
		"customDefaultValue": "",
		"calculateValue": "",
		"id": "eqjqv2v"
	},
	{
		"autofocus": false,
		"input": true,
		"tableView": true,
		"inputType": "number",
		"label": "Result c",
		"key": "c",
		"placeholder": "",
		"prefix": "",
		"suffix": "",
		"defaultValue": "",
		"protected": false,
		"persistent": true,
		"hidden": false,
		"clearOnHide": true,
		"validate": {
			"required": false,
			"min": "",
			"max": "",
			"step": "any",
			"integer": "",
			"multiple": "",
			"custom": "",
			"customPrivate": false
		},
		"type": "number",
		"labelPosition": "top",
		"tags": [],
		"conditional": {
			"show": "",
			"when": null,
			"eq": ""
		},
		"properties": {
			
		},
		"lockKey": true,
		"disabled": true,
		"isNew": false,
		"customClass": "",
		"multiple": false,
		"unique": false,
		"labelWidth": 30,
		"labelMargin": 3,
		"description": "",
		"errorLabel": "",
		"tooltip": "",
		"hideLabel": false,
		"tabindex": "",
		"dbIndex": false,
		"customDefaultValue": "",
		"calculateValue": "",
		"id": "eqppvbn"
	},
	{
		"autofocus": false,
		"input": true,
		"label": "Add using executeCustomEvent",
		"tableView": false,
		"key": "addusingcexeccustev",
		"size": "md",
		"leftIcon": "",
		"rightIcon": "",
		"block": false,
		"action": "custom",
		"disableOnInvalid": false,
		"theme": "primary",
		"type": "button",
		"tags": [],
		"conditional": {
			"show": "",
			"when": null,
			"eq": ""
		},
		"properties": {
			
		},
		"custom": "TogFormViewer.executeCustomAction('https://sasa-test-ete-fnc.azurewebsites.net/Add');",
		"placeholder": "",
		"prefix": "",
		"customClass": "",
		"suffix": "",
		"multiple": false,
		"defaultValue": null,
		"protected": false,
		"unique": false,
		"persistent": false,
		"hidden": false,
		"clearOnHide": true,
		"labelPosition": "top",
		"labelWidth": 30,
		"labelMargin": 3,
		"description": "",
		"errorLabel": "",
		"tooltip": "",
		"hideLabel": false,
		"tabindex": "",
		"disabled": false,
		"dbIndex": false,
		"customDefaultValue": "",
		"calculateValue": "",
		"validate": {
			"required": false,
			"custom": "",
			"customPrivate": false
		},
		"id": "eobbb1u"
	},
	{
		"input": true,
		"label": "Multiply",
		"tableView": false,
		"key": "mul",
		"size": "md",
		"leftIcon": "",
		"rightIcon": "",
		"block": false,
		"action": "event",
		"disableOnInvalid": false,
		"theme": "primary",
		"type": "button",
		"tags": [],
		"conditional": {
			"show": "",
			"when": null,
			"eq": ""
		},
		"properties": {
			"action": "Form('{formname}/{formversion}')/Multiplication"
		},
		"event": "Multiply",
		"lockKey": true,
		"customConditional": "show",
		"hideLabel": false,
		"autofocus": false,
		"placeholder": "",
		"prefix": "",
		"customClass": "",
		"suffix": "",
		"multiple": false,
		"defaultValue": null,
		"protected": false,
		"unique": false,
		"persistent": false,
		"hidden": false,
		"clearOnHide": true,
		"labelPosition": "top",
		"labelWidth": 30,
		"labelMargin": 3,
		"description": "",
		"errorLabel": "",
		"tooltip": "",
		"tabindex": "",
		"disabled": false,
		"dbIndex": false,
		"customDefaultValue": "",
		"calculateValue": "",
		"validate": {
			"required": false,
			"custom": "",
			"customPrivate": false
		},
		"id": "e2a0crc"
	}],
	"revisions": "",
	"_vid": 0,
	"access": [{
		"roles": ["599d5201a0434200072250b4",
		"599d5201a0434200072250b5",
		"599d5201a0434200072250b6"],
		"type": "read_all"
	}],
	"submissionAccess": [],
	"created": "2018-03-30T09:24:56.684Z",
	"_id": "5abe0268fad38b108803fb44",
	"title": "Calculate 2 numbers (V3)",
	"display": "form",
	"settings": {
		
	},
	"name": "calc",
	"path": "calc",
	"project": "599d5201a0434200072250b3",
	"modified": "2018-03-30T10:28:25.934Z",
	"machineName": "ewhyjxtmcncdriz:calc",
	"action": "Form('{formname}/{formversion}')/Subtraction",
	"properties": {
		"formtitle": "Calculate 2 numbers",
		"formhelp": "<p>This form is used to do calculation.</p>",
		"elearninglink": "https://en.wikipedia.org/wiki/Operation_(mathematics)",
		"elearningimagelink": "../logos/elearn.png",
		"processlink": "https://stackoverflow.com/questions/12256948/bitwise-operations-to-add-two-numbers",
		"processimagelink": "../logos/process.png"
	}
};