var headerObj = {
    "use outlook settings": false,
    "use user property extensions": true,
    "app launcher": true,
    "environment": true,
    "notifications": true,
    "settings": true,
    "help": true,
    "account": true,
    "theme settings": true,
    "feedback": false,
    "feedbackurl": "",
    "maximize": false,
    "mailbox photo": false,
    "themes": "../appcnfs/themes.json.js",
    "phraseapp": false,
    "phraseapp project id": "",
    "phraseapp prefix": "[[__",
    "phraseapp suffix": "__]]",
    "form width percent": "",
    "processtext": "Overridden text",
    "elearningtext": "",
    "autocalc": "",
    "calc_js_path": "../calc/calc_v12ab.js",
    "calc_js_setting": "",
    "calc_conf_path": "",
    "calc_conf_setting": "",
    "calc_api_path": "https://sasa-test-ete-fnc.azurewebsites.net/Calculation('{calcname}/{calcversion}')/Calculate",
    "action":"Form('{formname}/{formversion}')/Submit",
    "actionScript":"test1();",
    "action loading":"Form('{formname}/{formversion}')/Loading",
    "action loaded":"Form('{formname}/{formversion}')/Loaded",
    "bing maps key": "",
    "map wrapper id": "",
    "map route info wrapper id": "",
    "map country name": "",
    "map zoom": "",
    "map center pushpin": true,
    "map center pushpin title": "",
    "map center pushpin subtitle": "",
    "map center pushpin description": "",
    "map center latitude": "",
    "map center longitude": "",
    "map show info box": true,
    "map show traffic": "",
    "toggle menu": false,
    "triggerResizeChange": false,
    "userlangs": "../appcnfs/userlangs.json.js",
    "defaultLanguage": "EN-GB",
    "timezones": "../appcnfs/timezones.json.js",
    "defaultTimeZone": "UTC",
    "disableActionSpinner": false
};