var headerObj = {
    "use outlook settings": true,
    "ause user property extensions": true,
    "app launcher": true,
    "environment": true,
    "notifications": true,
    "settings": true,
    "help": true,
    "account": true,
    "theme settings": true,
    "feedback": true,
    "feedbackurl": "Feedback",
    "maximize": false,
    "mailbox photo": false,
    "themes": "../appcnfs/themes.json.js",
    "phraseapp": false,
    "phraseapp project id": "",
    "phraseapp prefix": "[[__",
    "phraseapp suffix": "__]]",
    "form width percent": "",
    "processtext": "Overridden text",
    "elearningtext": "",
    "aautocalc": "fieldchange",
    "acalc_js_path": "../calc/calc_v12ab.js",
    "acalc_js_path": "../calc/calcnonexisting.js",
    "calc_js_setting": "",
    "calc_conf_path": "",
    "calc_conf_setting": "",
    "acalc_api_path": "Calculation('{calcname}/{calcversion}')/Calculate",
    "aaction":"Form('{formname}/{formversion}')/Submit",
    "aaction local script" : "test1(togFormViewerEvent);",
    "action loading":"Form('{formname}/{formversion}')/Loading",
    "action loaded":"Form('{formname}/{formversion}')/Loaded",
    "aaction focus":"Form('{formname}/{formversion}')/Focus",
    "aaction focus local script":"",
    "aaction blur":"Form('{formname}/{formversion}')/Blur",
    "aaction blur local script":"",
    "aaction change":"Form('{formname}/{formversion}')/Change",
    "aaction change local script":"",
    "aaction search":"Form('{formname}/{formversion}-{eventtype}-{eventvalue}-{eventcontrolid}-{eventcontroltype}')/Search",
    "aaction search local script":"",
    "aaction showDropdown":"Form('{formname}/{formversion}')/ShowDropdown",
    "aaction showDropdown local script":"",
    "aaction click":"Form('{formname}/{formversion}')/Click",
    "aaction click local script":"",
    "aaction dblclick":"Form('{formname}/{formversion}')/DblClick",
    "aaction dblclick local script":"",
    "aaction contextMenu":"Form('{formname}/{formversion}')/ContextMenu",
    "aaction contextMenu local script":"",
    "aaction wheel":"Form('{formname}/{formversion}')/Wheel",
    "aaction wheel local script":"",
    "aaction mouseover":"Form('{formname}/{formversion}')/MouseOver",
    "aaction mouseover local script":"",
    "aaction mousedown":"Form('{formname}/{formversion}')/MouseDown",
    "aaction mousedown local script":"",
    "aaction mouseout":"Form('{formname}/{formversion}')/MouseOut",
    "aaction mouseout local script":"",
    "aaction mouseup":"Form('{formname}/{formversion}')/MouseUp",
    "aaction mouseup local script":"",
    "aaction mousemove":"Form('{formname}/{formversion}')/MouseMove",
    "aaction mousemove local script":"",
    "aaction mouseenter":"Form('{formname}/{formversion}')/MouseEnter",
    "aaction mouseenter local script":"",
    "aaction mouseleave":"Form('{formname}/{formversion}')/MouseLeave",
    "aaction mouseleave local script":"",
    "aaction keypress":"Form('{formname}/{formversion}')/KeyPress",
    "aaction keypress local script":"",
    "aaction keyup":"Form('{formname}/{formversion}')/KeyUp",
    "aaction keypup local script":"",
    "aaction keydown":"Form('{formname}/{formversion}')/KeyDown",
    "aaction keydown local script":"",
    "aaction input":"Form('{formname}/{formversion}')/Input",
    "aaction input local script":"",
    "aaction prevPage":"Form('{formname}/{formversion}')/PrevPage",
    "aaction prevPage local script":"",
    "aaction nextPage":"Form('{formname}/{formversion}')/NextPage",
    "aaction nextPage local script":"",
    "aaction componentError":"Form('{formname}/{formversion}')/ComponentError",
    "aaction componentError local script":"",
    "aaction beforeprint":"Form('{formname}/{formversion}')/BeforePrint",
    "aaction beforeprint local script":"",
    "aaction afterprint":"Form('{formname}/{formversion}')/AfterPrint",
    "aaction afterprint local script":"",
    "aaction resize":"Form('{formname}/{formversion}')/Resize",
    "aaction resize local script":"",
    "aaction select":"Form('{formname}/{formversion}')/Select",
    "aaction select local script":"",
    "aaction cut":"Form('{formname}/{formversion}')/Cut",
    "aaction cut local script":"",
    "aaction copy":"Form('{formname}/{formversion}')/Copy",
    "aaction copy local script":"",
    "aaction paste":"Form('{formname}/{formversion}')/Paste",
    "aaction paste local script":"",
    "aaction scroll":"Form('{formname}/{formversion}')/Scroll",
    "aaction scroll local script":"",
    "bing maps key": "",
    "map wrapper id": "",
    "map route info wrapper id": "",
    "map country name": "",
    "map zoom": "",
    "map center pushpin": true,
    "map center pushpin title": "",
    "map center pushpin subtitle": "",
    "map center pushpin description": "",
    "map center latitude": "",
    "map center longitude": "",
    "map show info box": true,
    "map show traffic": "",
    "toggle menu": false,
    "triggerResizeChange": false,
    "userlangs": "../appcnfs/userlangs.json.js",
    "defaultLanguage": "EN-GB",
    "timezones": "../appcnfs/timezones.json.js",
    "defaultTimeZone": "UTC",
    "disableActionSpinner": false,
    "menus": "",
    "langmenustop": "",
    "langmenusbottom": "",
    "test": false,
    "debug": false,
    "choicesOptions": "{\"searchResultLimit\": 10}",
    "sendForm": true,
    "formtranslation": "",
    "additional api function resource": "https://graph.microsoft.com",
    "additional api function url": "https://graph.microsoft.com/v1.0/me"    
};