var headerObj = {
    "use outlook settings": false,
    "use user property extensions": false,
    "app launcher": true,
    "environment": true,
    "notifications": true,
    "settings": true,
    "help": true,
    "account": true,
    "theme settings": true,
    "feedback": true,
    "feedbackurl": "Feedback",
    "maximize": false,
    "mailbox photo": false,
    "themes": "../appcnfs/themes.json.js",
    "phraseapp": false,
    "phraseapp project id": "",
    "phraseapp prefix": "[[__",
    "phraseapp suffix": "__]]",
    "form width percent": "",
    "processtext": "Overridden text",
    "elearningtext": "",
    "autocalc": "",
    "calc_js_path": "../calc/calc_v12ab.js",
    "calc_js_setting": "",
    "calc_conf_path": "",
    "calc_conf_setting": "",
    "calc_api_path": "https://sasa-test-ete-fnc.azurewebsites.net/Calculation('{calcname}/{calcversion}')/Calculate",
    "action":"Form('{formname}/{formversion}')/Submit",
    "action local script" : "test1();",
    "action loading":"Form('{formname}/{formversion}')/Loading",
    "action loaded":"Form('{formname}/{formversion}')/Loaded",
    "aaction focus":"Form('{formname}/{formversion}')/Focus",
    "action focus local script":"",
    "aaction blur":"Form('{formname}/{formversion}')/Blur",
    "action blur local script":"",
    "action change":"Form('{formname}/{formversion}')/Change",
    "action change local script":"",
    "aaction search":"Form('{formname}/{formversion}-{eventtype}-{eventvalue}-{eventcontrolid}-{eventcontroltype}')/Search",
    "action search local script":"",
    "action showDropdown":"Form('{formname}/{formversion}')/ShowDropdown",
    "action showDropdown local script":"",
    "aaction click":"Form('{formname}/{formversion}')/Click",
    "action click local script":"",
    "aaction dblclick":"Form('{formname}/{formversion}')/DblClick",
    "action dblclick local script":"",
    "aaction mouseover":"Form('{formname}/{formversion}')/MouseOver",
    "action mouseover local script":"",
    "aaction mousedown":"Form('{formname}/{formversion}')/MouseDown",
    "action mousedown local script":"",
    "aaction mouseout":"Form('{formname}/{formversion}')/MouseOut",
    "action mouseout local script":"",
    "aaction mouseup":"Form('{formname}/{formversion}')/MouseUp",
    "action mouseup local script":"",
    "aaction mousemove":"Form('{formname}/{formversion}')/MouseMove",
    "action mousemove local script":"",
    "aaction keypress":"Form('{formname}/{formversion}')/KeyPress",
    "action keypress local script":"",
    "aaction keyup":"Form('{formname}/{formversion}')/KeyUp",
    "action keypup local script":"",
    "aaction keydown":"Form('{formname}/{formversion}')/KeyDown",
    "action keydown local script":"",
    "action input":"Form('{formname}/{formversion}')/Input",
    "action input local script":"",
    "action prevPage":"Form('{formname}/{formversion}')/PrevPage",
    "action prevPage local script":"",
    "action nextPage":"Form('{formname}/{formversion}')/NextPage",
    "action nextPage local script":"",
    "aaction componentError":"Form('{formname}/{formversion}')/ComponentError",
    "action componentError local script":"",
    "action beforePrint":"Form('{formname}/{formversion}')/BeforePrint",
    "action beforePrint local script":"",
    "action afterPrint":"Form('{formname}/{formversion}')/AfterPrint",
    "action afterPrint local script":"",
    "bing maps key": "",
    "map wrapper id": "",
    "map route info wrapper id": "",
    "map country name": "",
    "map zoom": "",
    "map center pushpin": true,
    "map center pushpin title": "",
    "map center pushpin subtitle": "",
    "map center pushpin description": "",
    "map center latitude": "",
    "map center longitude": "",
    "map show info box": true,
    "map show traffic": "",
    "toggle menu": false,
    "triggerResizeChange": false,
    "userlangs": "../appcnfs/userlangs.json.js",
    "defaultLanguage": "EN-GB",
    "timezones": "../appcnfs/timezones.json.js",
    "defaultTimeZone": "UTC",
    "disableActionSpinner": false,
    "menus": "",
    "langmenustop": "",
    "langmenusbottom": "",
    "test": false,
    "debug": false,
    "choicesOptions": "{\"searchResultLimit\": 10}"

};